### ISSUE TITLE
Great shadow for content cards

### ISSUE THREAD

**Issue by juandc** [juandc/juandc.github.io#3]
Github section from [Carlos Cuesta Personal Page](https://carloscuesta.me).

The shadow is the following:

```scss
.box {
  border-top: 3px solid $DEFAULT_COLOR;
  box-shadow: 0 1px 2px rgba(0,0,0,0.15);
  &:hover {
    box-shadow: 0 15px 30px rgba(0,0,0,0.15);
  }
  &.violet {
    border-top-color: $COLOR;
  }
}
```
